StreamListRow Component
pclubiitk/Campus-Discuss-App pull request #21
Opened 2021-06-26 18:42 UTC by asharma8602

Please suggest improvements .
Also I had updated the packages to those which were added last year as i was facing typescript version issue.
Thanks

2021-06-27 10:45 UTC, mridul911 requested changes
We will be getting 'is_subscribed' also we can show that in right as a chip or button red for not subscribed and blue for other one. You can also add some background style.

2021-06-27 10:45 UTC, mridul911 commented on ui/screens/StreamListRow.tsx
> +          fontFamily: 'Baskerville Old Face'
Remove this font it crashes for android.

2021-06-27 10:45 UTC, mridul911 commented on ui/screens/StreamListRow.tsx
> +export default function App() {
use arrow functions like const StreamListRow = () => {}  and then export it so it can be used.

2021-07-21 19:10 UTC, 7shivamx commented
I'm taking up this issue

2021-07-26 19:54 UTC, closed without merging